[workspace]
members = [".", "crates/ironlung-protocol", "crates/ironlung-sandbox", "crates/ironlung-abi-check"]

[package]
name = "ironlung"
version = "0.1.0"
edition = "2021"

[features]
default = []
sandbox = []

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
panic = "abort"
strip = true
opt-level = "z"

[build-dependencies]
cc = "1.0"

[dependencies]
sc = "0.2"
talc = { version = "4.4", default-features = false, features = ["lock_api"] }
libc = { version = "0.2", default-features = false }
spin = "0.9"
ironlung-protocol = { path = "crates/ironlung-protocol" }
